# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import deepl_grpc.deepl_pb2 as deepl__pb2


class DeeplStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerResponse = channel.unary_unary(
            "/deepl.Deepl/GetServerResponse",
            request_serializer=deepl__pb2.Message.SerializeToString,
            response_deserializer=deepl__pb2.MessageResponse.FromString,
        )


class DeeplServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerResponse(self, request, context):
        """Deepl rpc service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DeeplServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetServerResponse": grpc.unary_unary_rpc_method_handler(
            servicer.GetServerResponse,
            request_deserializer=deepl__pb2.Message.FromString,
            response_serializer=deepl__pb2.MessageResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "deepl.Deepl", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Deepl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerResponse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/deepl.Deepl/GetServerResponse",
            deepl__pb2.Message.SerializeToString,
            deepl__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
